### ISSUE TITLE
Merge two charts in figure 1 in a single one

### ISSUE THREAD

**Issue by JJ** [mariosky/2017-User-Centered-IEC-#10]
If I have the data, I can include it in the same paper.

**Comment by mariosky** [comment]
You have the data :)

**Comment by mariosky** [comment]
JJ, Do you mean figures 4 and 5? Can I just do two subfigures in LaTeX?

**Comment by JJ** [comment]
The two with the number of PUTs by user. I need a single figure to save
space.

**Comment by JJ** [comment]
It is now Figure 1 in page 7, after removing some figures.
